//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.269
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Unturned;

public interface IDataHolder
{
    void Init();

    void AddBan(IBanEntry banEntry);
    void RemoveBan();

    int GetCredits(String steamId);
    void SaveCredits(String steamId, int count);

    void AddStructure(String structureStr);
	Dictionary<String, Unturned.IBanEntry> LoadBans();
}

