//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.0
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Xml.Serialization;

namespace Unturned.Entity
{
	[Serializable]
	public class PlayerClothes
	{
		[XmlAttribute("Shirt")]
		public int Shirt { get; set; }

		[XmlAttribute("Pants")]
		public int Pants { get; set; }

		[XmlAttribute("Hat")]
		public int Hat { get; set; }

		[XmlAttribute("Backpack")]
		public int Backpack { get; set; }

		[XmlAttribute("Vest")]
		public int Vest { get; set; }

		public PlayerClothes (int shirt, int pants, int hat, int backpack, int vest)
		{
			this.Shirt = shirt;
			this.Pants = pants;
			this.Hat = hat;
			this.Backpack = backpack;
			this.Vest = vest;
		}

		public PlayerClothes ()
		{
		}

		public override string ToString ()
		{
			return string.Format ("[PlayerClothes: Shirt={0}, Pants={1}, Hat={2}, Backpack={3}, Vest={4}]", Shirt, Pants, Hat, Backpack, Vest);
		}
		
	}
}

