//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.0
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Xml.Serialization;

namespace Unturned.Entity
{
	public class PlayerSkills
	{
		/*public Skill[] skills = new Skill[] { 
			new Skill("survivalist", "Survival", "Slower starvation and dehydration.", 4, 10), 
			new Skill("endurance", "Endurance", "Greater stamina and agility.", 5, 15), 
			new Skill("sneakybeaky", "Sneakybeaky", "Less agro and noise.", 6, 15), 
			new Skill("marksman", "Marksman", "Better accuracy and recoil.", 6, 15), 
			new Skill("warrior", "Warrior", "Do more and take less melee damage.", 4, 20), 
			new Skill("miner", "Outdoors", "Stronger mining and chopping.", 4, 15), 
			new Skill("crafting", "Craftsman", "Increases crafting smarts.", 2, 50), 
			new Skill("immunity", "Immunity", "Less disease and more vitality.", 4, 25)
		};*/

		[XmlAttribute("Experience")]
		public int Experience { get; set; }

		[XmlAttribute("Skills")]
		public String Skills { get; set; }

		public PlayerSkills()
		{
		}
	}
}

