//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.269
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Unturned;

namespace MysqlDatabase
{
	public class Database : IDataHolder
	{
        public void AddBan(IBanEntry banEntry)
        {
            throw new NotImplementedException();
        }

        public void RemoveBan()
        {
            throw new NotImplementedException();
        }

        public void AddStructure(string structureStr)
        {
            throw new NotImplementedException();
        }

        public int GetCredits(string steamId)
        {
            throw new NotImplementedException();
        }

        public void SaveCredits(string steamId, int count)
        {
            throw new NotImplementedException();
        }


        private string connectionString = "server=localhost;userid=root;password=;database=unturned";
		private MySqlConnection m_Connection;

        public void Init()
        {
            Logger.LogDatabase("Opening connection to the MySQL Server");

            try {
                m_Connection = new MySqlConnection(connectionString);
                m_Connection.Open();
                Logger.LogDatabase("Connected...");
            } 
            catch (MySqlException e) 
            {
                System.Console.WriteLine("Exception while making MySQL connection: " + e.Message );
            }
        }
        


        public void SaveBans(Dictionary<String, Unturned.IBanEntry> bans)
        {
            MySqlTransaction transaction = m_Connection.BeginTransaction();
            MySqlCommand cmd = new MySqlCommand(
                "INSERT INTO `bans` " +
                "(`steamid`, " +
                "`ban_date`, " +
                "`nickname`, " +
                "`banned_by`, " +
                "`ban_time`, " +
                "`reason`" +
                ") VALUES (@SteamID, @BanDate, @Nick, @BannedBy, @BanTime, @Reason)", 
                m_Connection, transaction);
            cmd.Prepare();

            foreach(KeyValuePair<String, IBanEntry> entry in bans) 
            {
                IBanEntry ban = entry.Value as Unturned.IBanEntry;
                cmd.Parameters.AddWithValue("@SteamID", ban.SteamID);
                cmd.Parameters.AddWithValue("@BanDate", ban.BanTime);
                cmd.Parameters.AddWithValue("@Nick", ban.Name);
                cmd.Parameters.AddWithValue("@BannedBy", ban.BannedBy);
                cmd.Parameters.AddWithValue("@BanTime", System.DateTime.Now);
                cmd.Parameters.AddWithValue("@Reason", ban.Reason );
                cmd.ExecuteNonQuery();
            }

            transaction.Commit();
        }
        
        public void SaveStructures(string structureStr)
        {
            String[] lines = structureStr.Split(';');

            MySqlTransaction transaction = m_Connection.BeginTransaction();
            MySqlCommand cmd = new MySqlCommand(
                "INSERT INTO `structures` " +
                "(`structure_str`)" +
                " VALUES (@StructureStr)", 
                m_Connection, transaction);
            cmd.Prepare();

            foreach (String line in lines)
            {
                cmd.Parameters.AddWithValue("@StructureStr", line);
                cmd.ExecuteNonQuery();
            }

            transaction.Commit();
        }
        
        public Dictionary<string, Unturned.IBanEntry> LoadBans()
        {
            Dictionary<String, IBanEntry> banList = new Dictionary<String, IBanEntry>();
            MySqlCommand cmd = new MySqlCommand();

            cmd.Connection = m_Connection;
            cmd.CommandText = "SELECT `steamid`, `ban_date`, `nickname`, `banned_by`, `ban_time`, `reason` FROM bans";

            MySqlDataReader reader = cmd.ExecuteReader();

            while (reader.Read()) {
                IBanEntry ban = new BanEntry(
                    reader.GetString(2), // NickName
                    reader.GetString(0), // Steam ID
                    reader.GetString(5), // Reason
                    reader.GetString(3), // Banned by
                    reader.GetDateTime(1) // BanTime
                );

                banList.Add( ban.SteamID, ban );
            }

            return banList;
        }

	}
}

