//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.269
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;
using System;
using System.Collections.Generic;
using Unturned;

[TestFixture]
public class DatabaseTest
{
    public Dictionary<String, INetworkBanned> banList;
    
    [Test]
    public void testBanDatabaseRead()
    {
        Console.WriteLine("Loading bans from file");
        banList = Database.provider.LoadBans();
        Console.WriteLine("Loaded {0} entry", banList.Count);
    }
    
    [Test]
    public void testBanDatabaseWrite()
    {
        if (banList.Count == 0)
        {
            banList.Add( "76561197994222727", new NetworkBanned("Julius Tiger", "76561197994222727", "Test Case of course", "76561197994222727", DateTime.Now));
        }
        
        Console.WriteLine("Saving...");
        //Database.provider.SaveBans(banList);
        Console.WriteLine("Done!");
    }
    
    [Test]
    public void testStructuresDatabaseWrite() 
    {
        //Database.provider.SaveStructures("asdf");
    }

}
