//
//  ItemTest.cs
//
//  Author:
//       Paál Gyula <paalgyula@gmail.com>
//
//  Copyright (c) 2015 (c) GW-Systems Kft. All Rights Reserved!
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.0
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;
using System;

namespace Tests
{
	[TestFixture()]
	public class ItemTest
	{
		[Test()]
		public void TestItemNames ()
		{
			for(int i=0;i<28000;i++)
			{
				String desc = ItemName.getName(i);

				if( desc.Contains("Sorry") )
					continue;

				Console.WriteLine( String.Format("INSERT INTO items (\"item_id\", \"name\", \"description\") VALUES ({0} ,'{1}', '{2}');", new object[]{
					i, desc.Replace("'", "''"), ItemDescription.getDescription(i, "").Replace("'", "''")
				}));
			}
		}
	}
}

