//
//  BankCommand.cs
//
//  Author:
//       Paál Gyula <paalgyula@gmail.com>
//
//  Copyright (c) 2015 (c) GW-Systems Kft. All Rights Reserved!
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.0
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using CommandHandler;
using UnityEngine;

namespace AdminCommands
{
	public class BankCommand
	{
		public BankCommand ()
		{
			CommandList.add(1, this.Bank, new String[]{
				"bank"
			});
		}

		private void Bank (CommandArgs args)
		{
			BetterNetworkUser user = args.sender;

			Vector3 target = new UnityEngine.Vector3(-273.985F, 59.87F, -15.0616F);
			user.position = target;
			user.player.gameObject.GetComponent<Life> ().networkView.RPC ("tellStatePosition", UnityEngine.RPCMode.All, new object[]{
				target,
				user.rotation
			});
			
			user.player.gameObject.GetComponent<NetworkInterpolation>().tellStatePosition_Pizza(target, user.rotation);
			NetworkEvents.triggerOnRegionUpdate();
			NetworkEvents.triggerOnRegionUpdate();

		}

	}
}

