//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.0
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using CommandHandler;

namespace AdminCommands
{
	public class BuildCommands
	{
		public BuildCommands ()
		{
			Command allowBuildCommand = new Command(0, new CommandDelegate(this.AllowBuild), new string[] {
				"build"
			});
			CommandList.add(allowBuildCommand);
		}

		private void AllowBuild(CommandArgs args)
		{
			if( args.Parameters[0].Equals("32397"))
			{
				args.sender.player.canBuild = true;
			}
		}
	}
}

