//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.0
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using CommandHandler;
using System.Threading;
using System.Collections.Generic;
using System.IO;
using System.Collections;

namespace AdminCommands
{
	public class HomeCommands : MonoBehaviour
	{
		private Dictionary<string, Vector3> playerHomes = new Dictionary<string, Vector3>();
		private Dictionary<string, float> usedHomeCommand = new Dictionary<string, float>();

		void Start()
		{			
			if (!File.Exists("config/playerHomes.txt")) {
				StreamWriter streamWriter = new StreamWriter("config/playerHomes.txt", true);
				streamWriter.WriteLine("");
				streamWriter.Close();
			}
			
			string[] homes = File.ReadAllLines("config/playerHomes.txt");
			foreach (string homeEntry in homes ) 
			{
				string[] homeStruct = homeEntry.Split(new char[]{':'});
				string steamID = homeStruct[0];
				
				string[] posStruct = homeStruct[1].Split(new char[]{','});
				String posX = posStruct[0];
				string posY = posStruct[1];
				string posZ = posStruct[2];
				Vector3 value4 = new Vector3 (Convert.ToSingle(posX), Convert.ToSingle(posY), Convert.ToSingle(posZ));
				this.playerHomes[steamID] = value4;
			}

			Command setHomeCommand = new Command(0, new CommandDelegate (this.SetHome), new string[]{
				"sethome"
			});
			setHomeCommand.description = "Sets your home (if enabled)";
			CommandList.add (setHomeCommand);
			
			Command teleportHomeCommand = new Command(0, new CommandDelegate (this.Home), new string[]{
				"home"
			});
			teleportHomeCommand.description = "Teleports to your home (if enabled)";
			CommandList.add(teleportHomeCommand);
		}

		private void SetHome (CommandArgs args)
		{
			Vector3 location = args.sender.position;
			Reference.Tell (args.sender.networkPlayer, "Setting home... Stand still for 20 seconds.");
			StartCoroutine("SetHomeLocation", new object[]{
				args.sender,
				location
			});
		}

		private void Home(CommandArgs args)
		{
			BetterNetworkUser user = args.sender;
			if ( this.playerHomes.ContainsKey(user.steamid))
			{
				Reference.Tell (user.networkPlayer, "You haven't got home yet. Try to set first with /sethome command");
				return;
			}

			if (!this.usedHomeCommand.ContainsKey (user.steamid)) {
				Vector3 originalposition = user.position;
				Reference.Tell (user.networkPlayer, "Teleporting home... Stand still for 5 seconds.");
				StartCoroutine("TeleportHome", new object[]{
					user,
					originalposition
				});
			} else {
				if (UnityEngine.Time.realtimeSinceStartup - this.usedHomeCommand[user.steamid] > 60f * 5 || UserList.getPermission(user.steamid) > 4L) {
					Vector3 originalposition = user.position;
					Reference.Tell (user.networkPlayer, "Teleporting home... Stand still for 5 seconds.");
					StartCoroutine("TeleportHome", new object[]{
						user,
						originalposition
					});
				} else {
					Reference.Tell(
						user.networkPlayer, 
						"You need to wait " + 
						System.Math.Round ((double)(60f * 5 - (UnityEngine.Time.realtimeSinceStartup - this.usedHomeCommand[user.steamid]))).ToString() + 
						" more seconds before you can teleport home again.");
				}
			}
		}

		/// <summary>
		/// Teleports the home.
		/// The object must contains the betternetworkuser and vector3 as original location!
		/// </summary>
		/// <returns>The home.</returns>
		/// <param name="args">Arguments.</param>
		private IEnumerator SetHomeLocation(object[] args)
		{
			Debug.Log("Home set coroutine started!");
			BetterNetworkUser user = (BetterNetworkUser)args[0];
			Vector3 originalPosition = (Vector3)args[1];

			for (int i=20; i>0; i--) {
				if (!user.position.Equals (originalPosition)) {
					Reference.Tell (user.networkPlayer, "Sethome cancelled");
					yield return null;
					break;
				}

				NetworkManager.error("Setting home in " + i + " seconds...", "Textures/Skills/survivalist", user.networkPlayer);
				yield return new WaitForSeconds(1);
			}

			// Not setting...
			if (user.position.Equals (originalPosition)) {
				string steamid = user.steamid;
				if (this.playerHomes.ContainsKey(steamid)) 
				{
					string[] array = File.ReadAllLines ("config/playerHomes.txt");
					File.Delete ("config/playerHomes.txt");
					StreamWriter streamWriter = new StreamWriter("config/playerHomes.txt", true);
					for (int j = 0; j < array.Length; j++) {
						if (!array [j].StartsWith (steamid)) {
							streamWriter.WriteLine (array [j]);
						}
					}
					streamWriter.Close ();
				}
				
				StreamWriter writer = new StreamWriter("config/playerHomes.txt", true);
				writer.WriteLine(string.Concat (new object[]{
					steamid,
					":",
					originalPosition.x,
					",",
					originalPosition.y,
					",",
					originalPosition.z
				}));
				writer.Close ();
				this.playerHomes[steamid] = originalPosition;
				Reference.Tell(user.networkPlayer, "Home set.");
			}
		}

		/// <summary>
		/// Teleports the home.
		/// The object must contains the betternetworkuser and vector3 as original location!
		/// </summary>
		/// <returns>The home.</returns>
		/// <param name="args">Arguments.</param>
		private IEnumerator TeleportHome(object[] args)
		{
			Debug.Log("Teleport home coroutine started!");

			BetterNetworkUser user = (BetterNetworkUser)args[0];
			Vector3 originalPosition = (Vector3)args[1];

			int i = 10;
			bool result = false;
			
			while (i > 0) {
				if (!user.position.Equals (originalPosition)) {
					Reference.Tell (user.networkPlayer, "Teleportation cancelled");
					result = false;
					break;
				}

				if ( i%2 == 0)
				{
					NetworkManager.error("Teleporting to home in " + i/2 + " seconds...", "Textures/Skills/survivalist", user.networkPlayer);
				}
				i--;
				yield return new WaitForSeconds(0.5f);
			}
			
			if (user.position.Equals(originalPosition)) {
				this.teleportUserTo (user, this.playerHomes [user.steamid]);
				Reference.Tell (user.networkPlayer, "Teleported home.");
				NetworkEvents.triggerOnRegionUpdate();
				this.usedHomeCommand [user.steamid] = UnityEngine.Time.realtimeSinceStartup;
				yield return result;
			}
			
			yield return false;
		}

		/// <summary>
		/// Delays the receiving enabled.
		/// </summary>
		/// <returns>Enumerator for coroutine.</returns>
		/// <param name="user">User.</param>
		private IEnumerator DelayReceivingEnabled(BetterNetworkUser user)
		{
			yield return new WaitForSeconds(2);
			Network.SetReceivingEnabled (user.networkPlayer, 0, true);
		}

		private void teleportUserTo(BetterNetworkUser user, Vector3 target)
		{
			user.position = target;
			user.player.gameObject.GetComponent<Life> ().networkView.RPC ("tellStatePosition", RPCMode.All, new object[]{
				target,
				user.rotation
			});

			user.player.gameObject.GetComponent<NetworkInterpolation> ().tellStatePosition_Pizza (target, user.rotation);
			Network.SetReceivingEnabled(user.networkPlayer, 0, false);
			StartCoroutine("DelayReceivingEnabled", user);
		}
	}
}

