//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.269
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;
using System;

namespace DatabaseHelper
{
    [TestFixture]
    public class DatabaseTest
    {
        [Test]
        public void TestCase()
        {
            IDataHolder dataHolder = new MysqlDatabase.Database();
        }
    }
}

